"""fix a typo

Revision ID: c3a72846af7b
Revises: de6aeb966ee7
Create Date: 2026-05-13 15:51:10.742694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3a72846af7b'
down_revision: Union[str, Sequence[str], None] = 'de6aeb966ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('refresh_tokens', 'update_at')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_at')
    op.add_column('refresh_tokens', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'updated_at')
    # ### end Alembic commands ###
